language: python
services: sqlite
env:
    - DJANGO='django>=1.8,<1.9'
    - DJANGO='django>=1.9,<1.10'
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install $DJANGO
    - python setup.py install
    - pip install coverage
    - pip install coveralls
    - pip install codecov
before_script:
    - cd tests/testproject
    - python manage.py makemigrations
script:
    - 'coverage run --source=dj_extensions,testapp manage.py test'
after_success:
    - coveralls
    - codecov
matrix:
    exclude:
        - python: 3.3
          env: DJANGO='django>=1.9,<1.10'